from pydantic import BaseModel, Field
from typing import List, Optional

class QAEntry(BaseModel):
    question: str = Field(description="The question generated by the AI")
    answer: Optional[str] = Field(default="Not provided", description="The answer provided by the user")

class ClinicalBrief(BaseModel):
    cc: List[QAEntry] = Field(default_factory=list, description="Chief Complaint Q&A pairs")
    hpi: List[QAEntry] = Field(default_factory=list, description="History of Present Illness Q&A pairs")
    ros: List[QAEntry] = Field(default_factory=list, description="Review of Systems Q&A pairs")
    summary: Optional[str] = Field(default="No summary provided.", description="A professional clinical summary of the entire interaction for the doctor's insight")
    patient_id: Optional[int] = Field(default=None, description="The ID of the patient")
    appointment_id: Optional[int] = Field(default=None, description="The ID of the appointment")
